### ISSUE TITLE
Crash on registering IRC transport

### ISSUE THREAD

**Issue by mcepl** [hanzz/spectrum2#79]
Whenever I register one-server-per-transport IRC, spectrum2 transport crashes with this traceback:
```
Reading symbols from /usr/bin/spectrum2...Reading symbols from /usr/lib/debug/usr/bin/spectrum2.debug...done.
done.
Missing separate debuginfo for 
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/17/a121b1f7bbb010f54735ffde3347b27b33884d
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/bin/spectrum2 -j freenode.cepl.eu /etc/spectrum2/transports/freenode.cfg'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fdc8b70ef38 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) () from /lib64/libstdc++.so.6
Missing separate debuginfos, use: debuginfo-install apr-1.4.8-3.el7.x86_64 apr-util-1.5.2-6.el7.x86_64 avahi-libs-0.6.31-15.el7.x86_64 boost-date-time-1.53.0-25.el7.x86_64 boost-filesystem-1.53.0-25.el7.x86_64 boost-program-options-1.53.0-25.el7.x86_64 boost-regex-1.53.0-25.el7.x86_64 boost-serialization-1.53.0-25.el7.x86_64 boost-signals-1.53.0-25.el7.x86_64 boost-system-1.53.0-25.el7.x86_64 boost-thread-1.53.0-25.el7.x86_64 cyrus-sasl-lib-2.1.26-19.2.el7.x86_64 dbus-libs-1.6.12-13.el7.x86_64 expat-2.1.0-8.el7.x86_64 glibc-2.17-106.el7_2.1.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.13.2-10.el7.x86_64 libcom_err-1.42.9-7.el7.x86_64 libcurl-7.29.0-25.el7.x86_64 libdb-5.3.21-19.el7.x86_64 libgcc-4.8.5-4.el7.x86_64 libicu-50.1.2-15.el7.x86_64 libidn-1.28-4.el7.x86_64 libpqxx-4.0.1-1.el7.x86_64 libselinux-2.2.2-6.el7.x86_64 libssh2-1.4.3-10.el7.x86_64 libstdc++-4.8.5-4.el7.x86_64 libuuid-2.23.2-26.el7.x86_64 log4cxx-0.10.0-16.el7.x86_64 mariadb-libs-5.5.44-2.el7.x86_64 nspr-4.10.8-2.el7_1.x86_64 nss-3.19.1-18.el7.x86_64 nss-softokn-freebl-3.16.2.3-13.el7_1.x86_64 nss-util-3.19.1-4.el7_1.x86_64 openldap-2.4.40-8.el7.x86_64 openssl-libs-1.0.1e-51.el7_2.1.x86_64 pcre-8.32-15.el7.x86_64 popt-1.13-16.el7.x86_64 postgresql-libs-9.2.14-1.el7_1.x86_64 protobuf-2.5.0-7.el7.x86_64 sqlite-3.7.17-8.el7.x86_64 swiften-3.0-0.3.beta2.el7.centos.x86_64 xz-libs-5.1.2-12alpha.el7.x86_64 zlib-1.2.7-15.el7.x86_64
(gdb) t a a bt

Thread 4 (Thread 0x7fdc7be75700 (LWP 5666)):
#0  0x00007fdc8bb736d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007fdc8eb26093 in Swift::PlatformDomainNameResolver::run() () from /lib64/libSwiften.so.3
#2  0x00007fdc8dedd24a in thread_proxy () from /lib64/libboost_thread-mt.so.1.53.0
#3  0x00007fdc8bb6fdc5 in start_thread () from /lib64/libpthread.so.0
#4  0x00007fdc8963621d in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7fdc7c676700 (LWP 5665)):
#0  0x00007fdc8bb736d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007fdc8eb30c93 in Swift::PlatformNATTraversalWorker::start() () from /lib64/libSwiften.so.3
#2  0x00007fdc8dedd24a in thread_proxy () from /lib64/libboost_thread-mt.so.1.53.0
#3  0x00007fdc8bb6fdc5 in start_thread () from /lib64/libpthread.so.0
#4  0x00007fdc8963621d in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7fdc7ce77700 (LWP 5664)):
#0  0x00007fdc896367f3 in epoll_wait () from /lib64/libc.so.6
#1  0x00007fdc8eaf617b in boost::asio::detail::epoll_reactor::run(bool, boost::asio::detail::op_queue<boost::asio::detail::task_io_service_operation>&) ()
   from /lib64/libSwiften.so.3
#2  0x00007fdc8eaf4670 in Swift::BoostIOServiceThread::doRun() () from /lib64/libSwiften.so.3
#3  0x00007fdc8dedd24a in thread_proxy () from /lib64/libboost_thread-mt.so.1.53.0
#4  0x00007fdc8bb6fdc5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007fdc8963621d in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7fdc8f5418c0 (LWP 5663)):
#0  0x00007fdc8b70ef38 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) () from /lib64/libstdc++.so.6
#1  0x000000000049963f in Transport::FormUtils::fieldValue (form=..., key="password", def="")
    at /usr/src/debug/spectrum2/spectrum/src/frontends/xmpp/formutils.cpp:203
#2  0x00000000004a3f70 in Transport::XMPPUserRegistration::handleSetRequest (this=0x2335060, from=..., to=..., id="191", payload=...)
    at /usr/src/debug/spectrum2/spectrum/src/frontends/xmpp/XMPPUserRegistration.cpp:316
#3  0x00000000004a86c6 in Swift::Responder<Swift::InBandRegistrationPayload>::handleIQ (this=0x2335100, iq=...) at /usr/include/Swiften/Queries/Responder.h:113
#4  0x00007fdc8e8a4588 in Swift::IQRouter::handleIQ(boost::shared_ptr<Swift::IQ>) () from /lib64/libSwiften.so.3
#5  0x00007fdc8e8a578c in boost::detail::function::void_function_obj_invoker1<boost::_bi::bind_t<void, boost::_mfi::mf1<void, Swift::IQRouter, boost::shared_ptr<Swift::IQ> >, boost::_bi::list2<boost::_bi::value<Swift::IQRouter*>, boost::arg<1> > >, void, boost::shared_ptr<Swift::IQ> >::invoke(boost::detail::function::function_buffer&, boost::shared_ptr<Swift::IQ>) () from /lib64/libSwiften.so.3
#6  0x000000000047456b in operator() (a0=..., this=<optimized out>) at /usr/include/boost/function/function_template.hpp:767
#7  operator()<boost::signals::detail::connection_slot_pair> (slot=..., this=0x7ffc0a1e9c50) at /usr/include/boost/signals/signal_template.hpp:119
#8  dereference (this=0x7ffc0a1e9c10) at /usr/include/boost/signals/detail/slot_call_iterator.hpp:61
#9  dereference<boost::signals::detail::slot_call_iterator<boost::signals::detail::call_bound1<void>::caller<boost::shared_ptr<Swift::IQ>, boost::function<void(boost::shared_ptr<Swift::IQ>)> >, boost::signals::detail::named_slot_map_iterator> > (f=...) at /usr/include/boost/iterator/iterator_facade.hpp:514
#10 operator* (this=0x7ffc0a1e9c10) at /usr/include/boost/iterator/iterator_facade.hpp:639
---Type <return> to continue, or q <return> to quit---
#11 postfix_increment_proxy (x=..., this=<synthetic pointer>) at /usr/include/boost/iterator/iterator_facade.hpp:145
#12 operator++<boost::signals::detail::slot_call_iterator<boost::signals::detail::call_bound1<void>::caller<boost::shared_ptr<Swift::IQ>, boost::function<void(boost::shared_ptr<Swift::IQ>)> >, boost::signals::detail::named_slot_map_iterator>, boost::signals::detail::unusable, boost::single_pass_traversal_tag, const boost::signals::detail::unusable&, long int> (i=...) at /usr/include/boost/iterator/iterator_facade.hpp:728
#13 operator()<boost::signals::detail::slot_call_iterator<boost::signals::detail::call_bound1<void>::caller<boost::shared_ptr<Swift::IQ>, boost::function<void(boost::shared_ptr<Swift::IQ>)> >, boost::signals::detail::named_slot_map_iterator> > (this=<optimized out>, 
    last=<error reading variable: access outside bounds of object referenced via synthetic pointer>, 
    first=<error reading variable: access outside bounds of object referenced via synthetic pointer>) at /usr/include/boost/last_value.hpp:49
#14 boost::signal1<void, boost::shared_ptr<Swift::IQ>, boost::last_value<void>, int, std::less<int>, boost::function<void (boost::shared_ptr<Swift::IQ>)> >::operator()(boost::shared_ptr<Swift::IQ>) (this=<optimized out>, a1=...) at /usr/include/boost/signals/signal_template.hpp:354
#15 0x00007fdc8ebb302e in Swift::ComponentSessionStanzaChannel::handleStanza(boost::shared_ptr<Swift::Stanza>) () from /lib64/libSwiften.so.3
#16 0x00007fdc8ebb34ec in boost::detail::function::void_function_obj_invoker1<boost::_bi::bind_t<void, boost::_mfi::mf1<void, Swift::ComponentSessionStanzaChannel, boost::shared_ptr<Swift::Stanza> >, boost::_bi::list2<boost::_bi::value<Swift::ComponentSessionStanzaChannel*>, boost::arg<1> > >, void, boost::shared_ptr<Swift::Stanza> >::invoke(boost::detail::function::function_buffer&, boost::shared_ptr<Swift::Stanza>) () from /lib64/libSwiften.so.3
#17 0x00007fdc8e8328d1 in boost::signal1<void, boost::shared_ptr<Swift::Stanza>, boost::last_value<void>, int, std::less<int>, boost::function<void (boost::shared_ptr<Swift::Stanza>)> >::operator()(boost::shared_ptr<Swift::Stanza>) () from /lib64/libSwiften.so.3
#18 0x00007fdc8ebb0656 in Swift::ComponentSession::handleElement(boost::shared_ptr<Swift::ToplevelElement>) () from /lib64/libSwiften.so.3
#19 0x00007fdc8ebb183d in boost::detail::function::void_function_obj_invoker1<boost::_bi::bind_t<void, boost::_mfi::mf1<void, Swift::ComponentSession, boost::shared_ptr<Swift::ToplevelElement> >, boost::_bi::list2<boost::_bi::value<boost::shared_ptr<Swift::ComponentSession> >, boost::arg<1> > >, void, boost::shared_ptr<Swift::ToplevelElement> >::invoke(boost::detail::function::function_buffer&, boost::shared_ptr<Swift::ToplevelElement>) () from /lib64/libSwiften.so.3
#20 0x00007fdc8f0d2b27 in operator() (a0=..., this=<optimized out>) at /usr/include/boost/function/function_template.hpp:767
#21 operator()<boost::signals::detail::connection_slot_pair> (slot=..., this=<optimized out>) at /usr/include/boost/signals/signal_template.hpp:119
#22 dereference (this=<optimized out>) at /usr/include/boost/signals/detail/slot_call_iterator.hpp:61
#23 dereference<boost::signals::detail::slot_call_iterator<boost::signals::detail::call_bound1<void>::caller<boost::shared_ptr<Swift::ToplevelElement>, boost::function<void(boost::shared_ptr<Swift::ToplevelElement>)> >, boost::signals::detail::named_slot_map_iterator> > (f=...)
    at /usr/include/boost/iterator/iterator_facade.hpp:514
#24 operator* (this=<optimized out>) at /usr/include/boost/iterator/iterator_facade.hpp:639
#25 postfix_increment_proxy (x=..., this=<synthetic pointer>) at /usr/include/boost/iterator/iterator_facade.hpp:145
#26 operator++<boost::signals::detail::slot_call_iterator<boost::signals::detail::call_bound1<void>::caller<boost::shared_ptr<Swift::ToplevelElement>, boost::function<void(boost::shared_ptr<Swift::ToplevelElement>)> >, boost::signals::detail::named_slot_map_iterator>, boost::signals::detail::unusable, boost::single_pass_traversal_tag, const boost::signals::detail::unusable&, long int> (i=...) at /usr/include/boost/iterator/iterator_facade.hpp:728
#27 operator()<boost::signals::detail::slot_call_iterator<boost::signals::detail::call_bound1<void>::caller<boost::shared_ptr<Swift::ToplevelElement>, boost::function<void(boost::shared_ptr<Swift::ToplevelElement>)> >, boost::signals::detail::named_slot_map_iterator> > (this=<optimized out>, last=..., first=...)
    at /usr/include/boost/last_value.hpp:49
#28 boost::signal1<void, boost::shared_ptr<Swift::ToplevelElement>, boost::last_value<void>, int, std::less<int>, boost::function<void (boost::shared_ptr<Swift::ToplevelElement>)> >::operator()(boost::shared_ptr<Swift::ToplevelElement>) (this=<optimized out>, a1=...) at /usr/include/boost/signals/signal_template.hpp:354
#29 0x00007fdc8e931e4b in Swift::BasicSessionStream::handleElementReceived(boost::shared_ptr<Swift::ToplevelElement>) () from /lib64/libSwiften.so.3
#30 0x00007fdc8e9328ac in boost::detail::function::void_function_obj_invoker1<boost::_bi::bind_t<void, boost::_mfi::mf1<void, Swift::BasicSessionStream, boost::shared_ptr<Swift::ToplevelElement> >, boost::_bi::list2<boost::_bi::value<Swift::BasicSessionStream*>, boost::arg<1> > >, void, boost::shared_ptr<Swift::ToplevelElement> >::invoke(boost::detail::function::function_buffer&, boost::shared_ptr<Swift::ToplevelElement>) () from /lib64/libSwiften.so.3
#31 0x00007fdc8f0d2b27 in operator() (a0=..., this=<optimized out>) at /usr/include/boost/function/function_template.hpp:767
---Type <return> to continue, or q <return> to quit---
#32 operator()<boost::signals::detail::connection_slot_pair> (slot=..., this=<optimized out>) at /usr/include/boost/signals/signal_template.hpp:119
#33 dereference (this=<optimized out>) at /usr/include/boost/signals/detail/slot_call_iterator.hpp:61
#34 dereference<boost::signals::detail::slot_call_iterator<boost::signals::detail::call_bound1<void>::caller<boost::shared_ptr<Swift::ToplevelElement>, boost::function<void(boost::shared_ptr<Swift::ToplevelElement>)> >, boost::signals::detail::named_slot_map_iterator> > (f=...)
    at /usr/include/boost/iterator/iterator_facade.hpp:514
#35 operator* (this=<optimized out>) at /usr/include/boost/iterator/iterator_facade.hpp:639
#36 postfix_increment_proxy (x=..., this=<synthetic pointer>) at /usr/include/boost/iterator/iterator_facade.hpp:145
#37 operator++<boost::signals::detail::slot_call_iterator<boost::signals::detail::call_bound1<void>::caller<boost::shared_ptr<Swift::ToplevelElement>, boost::function<void(boost::shared_ptr<Swift::ToplevelElement>)> >, boost::signals::detail::named_slot_map_iterator>, boost::signals::detail::unusable, boost::single_pass_traversal_tag, const boost::signals::detail::unusable&, long int> (i=...) at /usr/include/boost/iterator/iterator_facade.hpp:728
#38 operator()<boost::signals::detail::slot_call_iterator<boost::signals::detail::call_bound1<void>::caller<boost::shared_ptr<Swift::ToplevelElement>, boost::function<void(boost::shared_ptr<Swift::ToplevelElement>)> >, boost::signals::detail::named_slot_map_iterator> > (this=<optimized out>, last=..., first=...)
    at /usr/include/boost/last_value.hpp:49
#39 boost::signal1<void, boost::shared_ptr<Swift::ToplevelElement>, boost::last_value<void>, int, std::less<int>, boost::function<void (boost::shared_ptr<Swift::ToplevelElement>)> >::operator()(boost::shared_ptr<Swift::ToplevelElement>) (this=<optimized out>, a1=...) at /usr/include/boost/signals/signal_template.hpp:354
#40 0x00007fdc8eb8b79b in Swift::XMPPLayer::handleElement(boost::shared_ptr<Swift::ToplevelElement>) () from /lib64/libSwiften.so.3
#41 0x00007fdc8ea980ca in Swift::XMPPParser::handleEndElement(std::string const&, std::string const&) () from /lib64/libSwiften.so.3
#42 0x00007fdc8ea9ca4b in Swift::handleEndElement(void*, char const*) () from /lib64/libSwiften.so.3
#43 0x00007fdc8c3db080 in doContent () from /lib64/libexpat.so.1
#44 0x00007fdc8c3db9de in contentProcessor () from /lib64/libexpat.so.1
#45 0x00007fdc8c3dda1f in XML_ParseBuffer () from /lib64/libexpat.so.1
#46 0x00007fdc8ea9c7eb in Swift::ExpatParser::parse(std::string const&) () from /lib64/libSwiften.so.3
#47 0x00007fdc8ea9822e in Swift::XMPPParser::parse(std::string const&) () from /lib64/libSwiften.so.3
#48 0x00007fdc8eb8b648 in Swift::XMPPLayer::handleDataRead(std::vector<unsigned char, Swift::SafeAllocator<unsigned char> > const&) () from /lib64/libSwiften.so.3
#49 0x00007fdc8eb876ec in boost::detail::function::void_function_obj_invoker1<boost::_bi::bind_t<void, boost::_mfi::mf1<void, Swift::ConnectionLayer, boost::shared_ptr<std::vector<unsigned char, Swift::SafeAllocator<unsigned char> > > >, boost::_bi::list2<boost::_bi::value<Swift::ConnectionLayer*>, boost::arg<1> > >, void, boost::shared_ptr<std::vector<unsigned char, Swift::SafeAllocator<unsigned char> > > >::invoke(boost::detail::function::function_buffer&, boost::shared_ptr<std::vector<unsigned char, Swift::SafeAllocator<unsigned char> > >) () from /lib64/libSwiften.so.3
#50 0x00007fdc8eae1115 in boost::signal1<void, boost::shared_ptr<std::vector<unsigned char, Swift::SafeAllocator<unsigned char> > >, boost::last_value<void>, int, std::less<int>, boost::function<void (boost::shared_ptr<std::vector<unsigned char, Swift::SafeAllocator<unsigned char> > >)> >::operator()(boost::shared_ptr<std::vector<unsigned char, Swift::SafeAllocator<unsigned char> > >) () from /lib64/libSwiften.so.3
#51 0x00007fdc8eaeeb4a in boost::detail::function::void_function_obj_invoker0<boost::_bi::bind_t<boost::_bi::unspecified, boost::reference_wrapper<boost::signal<void (boost::shared_ptr<std::vector<unsigned char, Swift::SafeAllocator<unsigned char> > >), boost::last_value<void>, int, std::less<int>, boost::function<void (boost::shared_ptr<std::vector<unsigned char, Swift::SafeAllocator<unsigned char> > >)> > >, boost::_bi::list1<boost::_bi::value<boost::shared_ptr<std::vector<unsigned char, Swift::SafeAllocator<unsigned char> > > > > >, void>::invoke(boost::detail::function::function_buffer&) () from /lib64/libSwiften.so.3
#52 0x00007fdc8e9f2305 in Swift::invokeCallback(Swift::Event const&) () from /lib64/libSwiften.so.3
#53 0x00007fdc8e9f0787 in Swift::EventLoop::handleEvent(Swift::Event const&) () from /lib64/libSwiften.so.3
#54 0x00007fdc8e9f30c3 in Swift::SimpleEventLoop::doRun(bool) () from /lib64/libSwiften.so.3
#55 0x000000000045de21 in run (this=0x7ffc0a1eae90) at /usr/include/Swiften/EventLoop/SimpleEventLoop.h:24
#56 mainloop () at /usr/src/debug/spectrum2/spectrum/src/main.cpp:280
#57 0x0000000000458837 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/spectrum2/spectrum/src/main.cpp:510
(gdb)
```

**Comment by mcepl** [comment]
With non-empty password, it doesn't crash, but NickServ is apparently not called, because whenever I try to connect I get only "freenode.cepl.eu: Nickname is already in use". Any idea?

**Comment by mcepl** [comment]
Hmm, weird. libpurple backend still fails with:
```
==> /var/log/spectrum2/telegram.cepl.eu/backends/backend-1.log <==
9181: 2015-12-14 16:56:30,958 INFO  backend: +420604893825: Invalid protocol 'prpl-telegram'
```

**Comment by hanzz** [comment]
Because you are connected in freenode from another client with the same name?

**Comment by vitalyster** [comment]
original issue fixed in da9138fe29ae9e52982d48552e35ef8369d9c1f6

**Comment by mcepl** [comment]
> Because you are connected in freenode from another client with the same name?

Not sure about that, most likely while doing all crazy things with testing I got stuck somewhere and some IRC client did not disconnected from Freenode properly. Anyway, now it works, so this issue could be securely ignored.

**Comment by hanzz** [comment]
I'm still thinking whether we shouldn't fallback to "nickname_" in case the nickname chosen by the user is not available.
